const foodData = [
    { name: "白米", unit: "100g", calories: 168 },
    { name: "玄米", unit: "100g", calories: 165 },
    { name: "食パン", unit: "1枚", calories: 158 },
    { name: "牛肉(赤身)", unit: "100g", calories: 233 },
    { name: "鶏胸肉", unit: "100g", calories: 108 },
    { name: "味噌汁", unit: "1杯", calories: 40 },
    { name: "カレーライス", unit: "1皿", calories: 600 },
    { name: "サーモン", unit: "100g", calories: 208 },
    { name: "バナナ", unit: "1本", calories: 86 },
    { name: "りんご", unit: "1個", calories: 125 },
    { name: "豚肉(ロース)", unit: "100g", calories: 263 },
    { name: "鯖", unit: "100g", calories: 202 },
    { name: "さば", unit: "100g", calories: 202 },
    { name: "じゃがいも", unit: "100g", calories: 76 },
    { name: "もち", unit: "100g", calories: 235 },
    { name: "うどん", unit: "100g", calories:105  },
    { name: "そば", unit: "100g", calories: 132 },
    { name: "ラーメン", unit: "100g", calories: 149 },
    { name: "スパゲッティ", unit: "100g", calories:158 },
    { name: "鶏むね肉", unit: "100g", calories:108 },
    { name: "鶏もも肉", unit: "100g", calories:116 },
    { name: "牛もも肉", unit: "100g", calories:182 },
    { name: "鶏もも肉", unit: "100g", calories:116 },
    { name: "豚バラ肉", unit: "100g", calories:386 },
    { name: "鶏ささみ", unit: "100g", calories:105 },
    { name: "ローストビーフ", unit: "100g", calories: 196},
    { name: "まぐろ(赤身)", unit: "100g", calories: 125},
    { name: "まぐろ(中トロ)", unit: "100g", calories:344 },
    { name: "さけ", unit: "100g", calories:133 },
    { name: "ぶり", unit: "100g", calories:257 },
    { name: "まぐろ（赤身）", unit: "100g", calories: 125 },
    { name: "まぐろ（トロ）", unit: "100g", calories: 344 },
    { name: "鮭", unit: "100g", calories: 133 },
    { name: "ぶり", unit: "100g", calories: 257 },
    { name: "さば", unit: "100g", calories: 202 },
    { name: "いわし", unit: "100g", calories: 169 },
    { name: "うなぎ", unit: "1尾（150g）", calories: 446 },
    { name: "たこ", unit: "100g", calories: 76 },
    { name: "えび", unit: "100g", calories: 97 },
    { name: "いか", unit: "100g", calories: 88 },
    { name: "ほたて", unit: "100g", calories: 72 },
    { name: "卵", unit: "1個（60g）", calories: 75 },
    { name: "たまご", unit: "1個（60g）", calories: 75 },
    { name: "卵黄", unit: "1個（20g）", calories: 264 },
    { name: "卵白", unit: "1個（40g）", calories: 16 },
    { name: "牛乳", unit: "1杯（200ml）", calories: 122 },
    { name: "ヨーグルト（無糖）", unit: "100g", calories: 62 },
    { name: "プロセスチーズ", unit: "100g（1個 約20g）", calories: 339 },
    { name: "カマンベールチーズ", unit: "100g（1個 約100g）", calories: 310 },
    { name: "バター", unit: "10g（小さじ2杯）", calories: 72 },
    { name: "キャベツ", unit: "100g（1/4玉 約250g）", calories: 23 },
    { name: "レタス", unit: "100g（1玉 約300g）", calories: 12 },
    { name: "トマト", unit: "1個（150g）", calories: 30 },
    { name: "きゅうり", unit: "1本（100g）", calories: 14 },
    { name: "にんじん", unit: "1本（150g）", calories: 59 },
    { name: "じゃがいも", unit: "1個（130g）", calories: 101 },
    { name: "さつまいも", unit: "1本（150g）", calories: 198 },
    { name: "たまねぎ", unit: "1個（200g）", calories: 74 },
    { name: "ほうれん草", unit: "100g（1束 約200g）", calories: 20 },
    { name: "かぼちゃ", unit: "100g（1/8個 約250g）", calories: 91 },
    { name: "しめじ", unit: "100g（1パック 約100g）", calories: 18 },
    { name: "しいたけ", unit: "100g（1個 約20g）", calories: 18 },
    { name: "りんご", unit: "1個（300g）", calories: 150 },
    { name: "みかん", unit: "1個（100g）", calories: 45 },
    { name: "バナナ", unit: "1本（100g）", calories: 86 },
    { name: "ぶどう", unit: "100g（1房 約300g）", calories: 69 },
    { name: "いちご", unit: "5個（100g）", calories: 32 },
    { name: "スイカ", unit: "100g（1切れ 約300g）", calories: 37 },
    { name: "メロン（1/8個）", unit: "200g", calories: 85 },
    { name: "パイナップル", unit: "100g（1/4個 約300g）", calories: 51 },
    { name: "キウイフルーツ", unit: "1個（100g）", calories: 53 },
    { name: "アボカド", unit: "1個（150g）", calories: 281 },
    { name: "オートミール", unit: "100g", calories: 380 },
    { name: "玄米フレーク", unit: "100g", calories: 374 },
    { name: "コーンフレーク", unit: "100g", calories: 381 },
    { name: "ラム肉", unit: "100g", calories: 238 },
    { name: "合いびき肉", unit: "100g", calories: 224 },
    { name: "ベーコン", unit: "100g", calories: 405 },
    { name: "かつお", unit: "100g", calories: 165 },
    { name: "さんま", unit: "100g", calories: 310 },
    { name: "あじ", unit: "100g", calories: 121 },
    { name: "スキムミルク", unit: "100g", calories: 356 },
    { name: "アイスクリーム", unit: "100g", calories: 180 },
    { name: "ブロッコリー", unit: "100g", calories: 33 },
    { name: "ピーマン", unit: "100g", calories: 22 },
    { name: "ナス", unit: "100g", calories: 21 },
    { name: "マンゴー", unit: "100g", calories: 64 },
    { name: "ブルーベリー", unit: "100g", calories: 49 },
    { name: "チェリー", unit: "100g", calories: 63 },
    { name: "ひよこ豆", unit: "100g", calories: 364 },
    { name: "黒豆", unit: "100g", calories: 415 },
    { name: "ピスタチオ", unit: "100g", calories: 615 },
    { name: "緑茶", unit: "500ml", calories: 0 },
    { name: "スポーツドリンク", unit: "500ml", calories: 125 },
    { name: "ビール", unit: "350ml", calories: 140 },
    { name: "カステラ", unit: "100g", calories: 315 },
    { name: "プリン", unit: "100g", calories: 140 },
    { name: "チーズケーキ", unit: "100g", calories: 320 },
    { name: "フランスパン", unit: "100g", calories: 279 },
    { name: "ライ麦パン", unit: "100g", calories: 260 },
    { name: "クロワッサン", unit: "100g", calories: 406 },
    { name: "ホットケーキ", unit: "100g", calories: 261 },
    { name: "焼きそば", unit: "100g", calories: 172 },
    { name: "鴨肉", unit: "100g", calories: 244 },
    { name: "馬肉", unit: "100g", calories: 110 },
    { name: "ハム", unit: "100g", calories: 196 },
    { name: "ソーセージ", unit: "100g", calories: 301 },
    { name: "ビーフジャーキー", unit: "100g", calories: 328 },
    { name: "ほっけ", unit: "100g", calories: 151 },
    { name: "しらす", unit: "100g", calories: 113 },
    { name: "ちりめんじゃこ", unit: "100g", calories: 189 },
    { name: "明太子", unit: "100g", calories: 129 },
    { name: "はまぐり", unit: "100g", calories: 30 },
    { name: "大豆", unit: "100g", calories: 417 },
    { name: "エンドウ豆", unit: "100g", calories: 81 },
    { name: "そら豆", unit: "100g", calories: 84 },
    { name: "くるみ（ロースト）", unit: "100g", calories: 650 },
    { name: "マカダミアナッツ", unit: "100g", calories: 718 },
    { name: "カリフラワー", unit: "100g", calories: 30 },
    { name: "アスパラガス", unit: "100g", calories: 22 },
    { name: "レンコン", unit: "100g", calories: 66 },
    { name: "ゴボウ", unit: "100g", calories: 65 },
    { name: "もやし", unit: "100g", calories: 14 },
    { name: "柿", unit: "100g", calories: 60 },
    { name: "プルーン", unit: "100g", calories: 51 },
    { name: "ライチ", unit: "100g", calories: 66 },
    { name: "ザクロ", unit: "100g", calories: 83 },
    { name: "グレープフルーツ", unit: "100g", calories: 38 },
    { name: "烏龍茶", unit: "500ml", calories: 0 },
    { name: "紅茶（ストレート）", unit: "500ml", calories: 2 },
    { name: "ココア", unit: "200ml", calories: 85 },
    { name: "カフェオレ", unit: "200ml", calories: 96 },
    { name: "エナジードリンク", unit: "250ml", calories: 112 },
    { name: "どら焼き", unit: "100g", calories: 267 },
    { name: "羊羹", unit: "100g", calories: 290 },
    { name: "ミルクチョコレート", unit: "100g", calories: 558 },
    { name: "ポップコーン（バター）", unit: "100g", calories: 535 },
    { name: "ショートブレッド", unit: "100g", calories: 502 },
    { name: "タコライス", unit: "1皿", calories: 780 },
    { name: "ビビンバ", unit: "1杯", calories: 640 },
    { name: "チャーハン", unit: "1皿", calories: 740 },
    { name: "親子丼", unit: "1杯", calories: 720 },
    { name: "牛丼", unit: "1杯", calories: 860 },
    { name: "おにぎり", unit: "1個", calories: 180 },
    { name: "天丼", unit: "1杯", calories: 950 },
    { name: "カツ丼", unit: "1杯", calories: 1100 },
    { name: "パエリア", unit: "1皿", calories: 650 },
    { name: "リゾット", unit: "1皿", calories: 520 },
    { name: "ハンバーグ", unit: "1個", calories: 350 },
    { name: "ローストチキン", unit: "100g", calories: 230 },
    { name: "チキンカツ", unit: "1枚", calories: 450 },
    { name: "焼き鳥（ねぎま）", unit: "1本", calories: 80 },
    { name: "焼き鳥（皮）", unit: "1本", calories: 150 },
    { name: "牛ステーキ", unit: "100g", calories: 280 },
    { name: "豚の生姜焼き", unit: "1皿", calories: 520 },
    { name: "からあげ", unit: "1個", calories: 90 },
    { name: "スペアリブ", unit: "100g", calories: 320 },
    { name: "レバニラ炒め", unit: "1皿", calories: 450 },
    { name: "サーモンのムニエル", unit: "1切れ", calories: 320 },
    { name: "アジフライ", unit: "1枚", calories: 290 },
    { name: "かつおのたたき", unit: "100g", calories: 120 },
    { name: "鮭の塩焼き", unit: "1切れ", calories: 180 },
    { name: "イカリングフライ", unit: "100g", calories: 280 },
    { name: "カニクリームコロッケ", unit: "1個", calories: 180 },
    { name: "ホタテのバター焼き", unit: "1個", calories: 130 },
    { name: "エビチリ", unit: "1皿", calories: 420 },
    { name: "牡蠣フライ", unit: "1個", calories: 120 },
    { name: "ウナギの白焼き", unit: "100g", calories: 293 },
    { name: "モンブラン", unit: "1個", calories: 380 },
    { name: "チーズタルト", unit: "1個", calories: 340 },
    { name: "シュークリーム", unit: "1個", calories: 280 },
    { name: "エクレア", unit: "1個", calories: 290 },
    { name: "ロールケーキ", unit: "1個", calories: 250 },
    { name: "バウムクーヘン", unit: "100g", calories: 360 },
    { name: "アップルパイ", unit: "1個", calories: 280 },
    { name: "アイスモナカ", unit: "1個", calories: 210 },
    { name: "チョコブラウニー", unit: "1個", calories: 320 },
    { name: "カステラ", unit: "1切れ", calories: 140 },
    { name: "すき焼き", unit: "1皿", calories: 850 },
    { name: "しゃぶしゃぶ", unit: "1皿", calories: 580 },
    { name: "ローストポーク", unit: "100g", calories: 260 },
    { name: "チキン南蛮", unit: "1枚", calories: 520 },
    { name: "ミートローフ", unit: "1切れ", calories: 350 },
    { name: "豚角煮", unit: "1皿", calories: 540 },
    { name: "ビーフシチュー", unit: "1皿", calories: 500 },
    { name: "タンドリーチキン", unit: "100g", calories: 290 },
    { name: "ホルモン炒め", unit: "1皿", calories: 470 },
    { name: "ラムチョップ", unit: "1本", calories: 330 },
    { name: "アサリの酒蒸し", unit: "1皿", calories: 190 },
    { name: "鯛のカルパッチョ", unit: "1皿", calories: 280 },
    { name: "タコの酢の物", unit: "1皿", calories: 120 },
    { name: "ホッケの塩焼き", unit: "1切れ", calories: 210 },
    { name: "ししゃも", unit: "1本", calories: 70 },
    { name: "マグロ漬け丼", unit: "1杯", calories: 620 },
    { name: "イクラ丼", unit: "1杯", calories: 680 },
    { name: "エビフライ", unit: "1本", calories: 180 },
    { name: "カキの酒蒸し", unit: "1皿", calories: 200 },
    { name: "イワシの南蛮漬け", unit: "1皿", calories: 330 },
    { name: "五目ごはん", unit: "1杯", calories: 320 },
    { name: "雑炊", unit: "1杯", calories: 250 },
    { name: "炊き込みご飯", unit: "1杯", calories: 310 },
    { name: "おかゆ", unit: "1杯", calories: 150 },
    { name: "茶漬け", unit: "1杯", calories: 180 },
    { name: "焼肉（カルビ）", unit: "100g", calories: 517 },
    { name: "焼肉（ロース）", unit: "100g", calories: 280 },
    { name: "焼肉（ハラミ）", unit: "100g", calories: 346 },
    { name: "牛タン", unit: "100g", calories: 269 },
    { name: "チキンソテー", unit: "1枚", calories: 400 },
    { name: "イワシの塩焼き", unit: "1尾", calories: 210 },
    { name: "カツオのたたき", unit: "1皿", calories: 120 },
    { name: "ブリの照り焼き", unit: "1切れ", calories: 250 },
    { name: "ホタテの刺身", unit: "100g", calories: 90 },
    { name: "サバの味噌煮", unit: "1切れ", calories: 280 },
    { name: "チーズトースト", unit: "1枚", calories: 320 },
    { name: "オムカレー", unit: "1皿", calories: 750 },
    { name: "フレンチトースト", unit: "1枚", calories: 340 },
    { name: "クリームシチュー", unit: "1杯", calories: 420 },
    { name: "カッテージチーズ", unit: "100g", calories: 98 },
    { name: "野菜炒め", unit: "1皿", calories: 220 },
    { name: "根菜スープ", unit: "1杯", calories: 180 },
    { name: "ポテトサラダ", unit: "1皿", calories: 250 },
    { name: "ナムル", unit: "1皿", calories: 150 },
    { name: "ピクルス", unit: "100g", calories: 90 },
    { name: "杏仁豆腐", unit: "1個", calories: 160 },
    { name: "わらび餅", unit: "100g", calories: 170 },
    { name: "みたらし団子", unit: "1本", calories: 120 },
    { name: "大学芋", unit: "100g", calories: 280 },
    { name: "クレープ", unit: "1枚", calories: 290 },
    { name: "チキンライス", unit: "1皿", calories: 600 },
    { name: "天津飯", unit: "1皿", calories: 720 },
    { name: "ガパオライス", unit: "1皿", calories: 680 },
    { name: "ドライカレー", unit: "1皿", calories: 620 },
    { name: "ハヤシライス", unit: "1皿", calories: 750 },
    { name: "ポークソテー", unit: "1枚", calories: 450 },
    { name: "ハムカツ", unit: "1枚", calories: 320 },
    { name: "ソーセージ盛り合わせ", unit: "1皿", calories: 600 },
    { name: "ローストラム", unit: "100g", calories: 290 },
    { name: "ミートボール", unit: "5個", calories: 350 },
    { name: "エビマヨ", unit: "1皿", calories: 450 },
    { name: "タラのムニエル", unit: "1切れ", calories: 280 },
    { name: "サンマの蒲焼き", unit: "1尾", calories: 360 },
    { name: "タコの唐揚げ", unit: "100g", calories: 310 },
    { name: "ホッケの開き", unit: "1尾", calories: 420 },
    { name: "バターロール", unit: "1個", calories: 180 },
    { name: "スクランブルエッグ", unit: "1皿", calories: 250 },
    { name: "エッグベネディクト", unit: "1皿", calories: 450 },
    { name: "モッツァレラチーズ", unit: "100g", calories: 280 },
    { name: "チーズスティック", unit: "3本", calories: 350 },
    { name: "コールスロー", unit: "1皿", calories: 150 },
    { name: "トマトスープ", unit: "1杯", calories: 120 },
    { name: "オニオングラタンスープ", unit: "1杯", calories: 250 },
    { name: "きんぴらレンコン", unit: "1皿", calories: 200 },
    { name: "ブロッコリーのごま和え", unit: "1皿", calories: 180 },
    { name: "ガトーショコラ", unit: "1個", calories: 350 },
    { name: "抹茶パフェ", unit: "1個", calories: 420 },
    { name: "ティラミスパンケーキ", unit: "1皿", calories: 560 },
    { name: "マドレーヌ", unit: "1個", calories: 150 },
    { name: "カスタードクリームパン", unit: "1個", calories: 300 },
    { name: "トルティーヤ", unit: "1枚", calories: 180 },
    { name: "ピタパン", unit: "1枚", calories: 165 },
    { name: "マッシュポテト", unit: "1皿", calories: 200 },
    { name: "パンケーキ", unit: "1枚", calories: 210 },
    { name: "おにぎり（梅）", unit: "1個", calories: 180 },
    { name: "ラムチョップ", unit: "1本", calories: 330 },
    { name: "スモークチキン", unit: "100g", calories: 250 },
    { name: "スペアリブ", unit: "100g", calories: 350 },
    { name: "ミートソース", unit: "1皿", calories: 480 },
    { name: "焼き鳥（砂肝）", unit: "1本", calories: 90 },
    { name: "サバ缶（水煮）", unit: "1缶", calories: 210 },
    { name: "タコ焼き", unit: "5個", calories: 300 },
    { name: "イワシの蒲焼き", unit: "1尾", calories: 250 },
    { name: "アサリの味噌汁", unit: "1杯", calories: 80 },
    { name: "しらすおろし", unit: "1皿", calories: 110 },
    { name: "リコッタチーズ", unit: "100g", calories: 174 },
    { name: "ホットミルク", unit: "1杯", calories: 120 },
    { name: "カフェラテ", unit: "1杯", calories: 180 },
    { name: "チーズケーキ", unit: "1個", calories: 320 },
    { name: "チョコレートドリンク", unit: "200ml", calories: 210 },
    { name: "かぼちゃスープ", unit: "1杯", calories: 150 },
    { name: "ほうれん草の胡麻和え", unit: "1皿", calories: 120 },
    { name: "ラタトゥイユ", unit: "1皿", calories: 190 },
    { name: "ポテトグラタン", unit: "1皿", calories: 380 },
    { name: "キャロットラペ", unit: "1皿", calories: 160 },
    { name: "シナモンロール", unit: "1個", calories: 420 },
    { name: "ワッフル", unit: "1枚", calories: 330 },
    { name: "クリームブリュレ", unit: "1個", calories: 290 },
    { name: "ハニートースト", unit: "1皿", calories: 720 },
    { name: "ミルフィーユ", unit: "1個", calories: 380 },
    { name: "玄米おにぎり", unit: "1個", calories: 190 },
    { name: "ナン", unit: "1枚", calories: 310 },
    { name: "フォカッチャ", unit: "1枚", calories: 250 },
    { name: "グリーンカレー", unit: "1皿", calories: 720 },
    { name: "チキンフォー", unit: "1杯", calories: 450 },
    { name: "ローストダック", unit: "100g", calories: 320 },
    { name: "ビーフストロガノフ", unit: "1皿", calories: 600 },
    { name: "チキンナゲット", unit: "5個", calories: 400 },
    { name: "ターキーハム", unit: "100g", calories: 160 },
    { name: "焼き鳥（レバー）", unit: "1本", calories: 120 },
    { name: "カニの味噌汁", unit: "1杯", calories: 90 },
    { name: "イカ刺し", unit: "100g", calories: 95 },
    { name: "カツオの竜田揚げ", unit: "1皿", calories: 350 },
    { name: "ムール貝のワイン蒸し", unit: "1皿", calories: 220 },
    { name: "アンチョビピザ", unit: "1枚", calories: 600 },
    { name: "バターチキンカレー", unit: "1皿", calories: 750 },
    { name: "チーズフォンデュ", unit: "1皿", calories: 800 },
    { name: "ヨーグルトパフェ", unit: "1個", calories: 350 },
    { name: "カッテージチーズサラダ", unit: "1皿", calories: 230 },
    { name: "エッグサンド", unit: "1個", calories: 290 },
    { name: "バーニャカウダ", unit: "1皿", calories: 280 },
    { name: "ビーツスープ", unit: "1杯", calories: 150 },
    { name: "枝豆の塩茹で", unit: "100g", calories: 135 },
    { name: "ズッキーニグリル", unit: "1皿", calories: 160 },
    { name: "紫キャベツのサラダ", unit: "1皿", calories: 120 },
    { name: "スフレチーズケーキ", unit: "1個", calories: 300 },
    { name: "レモンタルト", unit: "1個", calories: 350 },
    { name: "フィナンシェ", unit: "1個", calories: 180 },
    { name: "メロンパン", unit: "1個", calories: 450 },
    { name: "フルーツパウンドケーキ", unit: "1切れ", calories: 320 },
    { name: "オートミールパンケーキ", unit: "1枚", calories: 220 },
    { name: "ベーグル", unit: "1個", calories: 270 },
    { name: "ライスヌードル", unit: "100g", calories: 180 },
    { name: "ターメリックライス", unit: "1杯", calories: 240 },
    { name: "キノアサラダ", unit: "1皿", calories: 320 },
    { name: "ダックコンフィ", unit: "100g", calories: 350 },
    { name: "スパイシーチキン", unit: "1枚", calories: 480 },
    { name: "ハンバーグステーキ", unit: "1個", calories: 500 },
    { name: "チキンカチャトーラ", unit: "1皿", calories: 450 },
    { name: "ジンギスカン", unit: "1皿", calories: 700 },
    { name: "ロブスターグリル", unit: "1尾", calories: 450 },
    { name: "ホタテのバター醤油焼き", unit: "1個", calories: 150 },
    { name: "カニクリームパスタ", unit: "1皿", calories: 680 },
    { name: "牡蠣のグラタン", unit: "1皿", calories: 520 },
    { name: "イカスミパスタ", unit: "1皿", calories: 600 },
    { name: "スモークチーズ", unit: "100g", calories: 320 },
    { name: "ギリシャヨーグルト", unit: "100g", calories: 100 },
    { name: "チーズトルティーヤ", unit: "1枚", calories: 400 },
    { name: "クアトロフォルマッジ", unit: "1枚", calories: 850 },
    { name: "スフレオムレツ", unit: "1皿", calories: 250 },
    { name: "アボカドトースト", unit: "1枚", calories: 350 },
    { name: "カプレーゼサラダ", unit: "1皿", calories: 200 },
    { name: "ローストビーツ", unit: "1皿", calories: 180 },
    { name: "ザワークラウト", unit: "100g", calories: 100 },
    { name: "ニンニクのロースト", unit: "1皿", calories: 120 },
    { name: "ベイクドアラスカ", unit: "1個", calories: 500 },
    { name: "マカダミアナッツクッキー", unit: "1枚", calories: 200 },
    { name: "ピーカンパイ", unit: "1切れ", calories: 400 },
    { name: "バスクチーズケーキ", unit: "1個", calories: 380 },
    { name: "ホワイトチョコムース", unit: "1個", calories: 320 },
    { name: "もち麦ごはん", unit: "1杯", calories: 180 },
    { name: "バスマティライス", unit: "100g", calories: 150 },
    { name: "豆乳グラタン", unit: "1皿", calories: 500 },
    { name: "キムパ", unit: "1本", calories: 350 },
    { name: "パクチーライス", unit: "1皿", calories: 320 },
    { name: "ターキーのロースト", unit: "100g", calories: 200 },
    { name: "スモークベーコン", unit: "100g", calories: 410 },
    { name: "ハラミステーキ", unit: "100g", calories: 380 },
    { name: "ポークビンダルー", unit: "1皿", calories: 600 },
    { name: "鴨のオレンジソース", unit: "1皿", calories: 650 },
    { name: "カニのパスタ", unit: "1皿", calories: 680 },
    { name: "タラのフライ", unit: "1切れ", calories: 350 },
    { name: "エビグラタン", unit: "1皿", calories: 550 },
    { name: "ムール貝のスープ", unit: "1杯", calories: 250 },
    { name: "ホタルイカの酢味噌和え", unit: "1皿", calories: 180 },
    { name: "ココナッツヨーグルト", unit: "100g", calories: 120 },
    { name: "クリームチーズディップ", unit: "100g", calories: 340 },
    { name: "ブルーチーズ", unit: "100g", calories: 350 },
    { name: "エッグタルト", unit: "1個", calories: 280 },
    { name: "マンゴープリン", unit: "1個", calories: 240 },
    { name: "ロメインレタスのサラダ", unit: "1皿", calories: 140 },
    { name: "ズッキーニパスタ", unit: "1皿", calories: 180 },
    { name: "ナスのオーブン焼き", unit: "1皿", calories: 220 },
    { name: "かぼちゃの煮物", unit: "1皿", calories: 200 },
    { name: "レンコンの素揚げ", unit: "1皿", calories: 250 },
    { name: "ピーナッツバタークッキー", unit: "1枚", calories: 230 },
    { name: "マロンパイ", unit: "1個", calories: 370 },
    { name: "ゴーフレット", unit: "1個", calories: 280 },
    { name: "チョコレートクロワッサン", unit: "1個", calories: 420 },
    { name: "クリームパイ", unit: "1個", calories: 390 },
    { name: "クスクス", unit: "100g", calories: 112 },
    { name: "ハヤシライス", unit: "1皿", calories: 700 },
    { name: "チーズリゾット", unit: "1皿", calories: 650 },
    { name: "インディカ米", unit: "100g", calories: 130 },
    { name: "大麦フレーク", unit: "100g", calories: 340 },
    { name: "ローストビーフサンド", unit: "1個", calories: 480 },
    { name: "スペアリブの煮込み", unit: "1皿", calories: 750 },
    { name: "骨付きラムチョップ", unit: "1本", calories: 420 },
    { name: "ターキーステーキ", unit: "1枚", calories: 320 },
    { name: "ビーフカツ", unit: "1枚", calories: 550 },
    { name: "マグロのステーキ", unit: "1枚", calories: 350 },
    { name: "シーフードカレー", unit: "1皿", calories: 680 },
    { name: "カレイの煮付け", unit: "1切れ", calories: 280 },
    { name: "ホタテクリームコロッケ", unit: "1個", calories: 350 },
    { name: "エビとブロッコリーの炒め物", unit: "1皿", calories: 400 },
    { name: "ミモレットチーズ", unit: "100g", calories: 385 },
    { name: "アーモンドミルク", unit: "200ml", calories: 60 },
    { name: "カマンベールフライ", unit: "1個", calories: 280 },
    { name: "スクランブルエッグトースト", unit: "1枚", calories: 350 },
    { name: "バナナシェイク", unit: "1杯", calories: 320 },
    { name: "ブロッコリースープ", unit: "1杯", calories: 150 },
    { name: "カボチャのクリーム煮", unit: "1皿", calories: 280 },
    { name: "キャベツステーキ", unit: "1皿", calories: 200 },
    { name: "スパイシーポテト", unit: "1皿", calories: 330 },
    { name: "ビーツとフェタチーズのサラダ", unit: "1皿", calories: 250 },
    { name: "オペラケーキ", unit: "1個", calories: 450 },
    { name: "トリュフチョコレート", unit: "1個", calories: 80 },
    { name: "クランベリークッキー", unit: "1枚", calories: 200 },
    { name: "ストロベリータルト", unit: "1個", calories: 420 },
    { name: "ハチミツレモンゼリー", unit: "1個", calories: 150 },
    { name: "ドラゴンフルーツ", unit: "1個", calories: 198 },
  { name: "スターフルーツ", unit: "1個", calories: 38 },
  { name: "パッションフルーツ", unit: "1個", calories: 17 },
  { name: "グアバ", unit: "1個", calories: 112 },
  { name: "ポポー", unit: "1個", calories: 120 },
  { name: "フィンガーライム", unit: "1個", calories: 3 },
  { name: "ジャボチカバ", unit: "1個", calories: 1 },
  { name: "クコの実（ゴジベリー）", unit: "1個", calories: 2 },
  { name: "ブラックベリー", unit: "1個", calories: 2 },
  { name: "ラズベリー", unit: "1個", calories: 2 },
  { name: "クランベリー", unit: "1個", calories: 0.5 },
  { name: "ボイセンベリー", unit: "1個", calories: 3 },
  { name: "アセロラ", unit: "1個", calories: 2 },
  { name: "サクランボ（ビングチェリー）", unit: "1個", calories: 5 },
  { name: "ログァット（ビワ）", unit: "1個", calories: 9 },
  { name: "フェイジョア", unit: "1個", calories: 23 },
  { name: "カラマンシー", unit: "1個", calories: 9 },
  { name: "サワーソップ", unit: "1個", calories: 660 },
  { name: "チェリモヤ", unit: "1個", calories: 225 },
  { name: "サポジラ", unit: "1個", calories: 125 },
  { name: "サポテ", unit: "1個", calories: 180 },
  { name: "カカドゥプラム", unit: "1個", calories: 9 },
  { name: "クプアス", unit: "1個", calories: 975 },
  { name: "ランブータン", unit: "1個", calories: 24 },
  { name: "マンゴスチン", unit: "1個", calories: 58 },
  { name: "ジャックフルーツ", unit: "1個", calories: 9500 },
  { name: "メロンペポ", unit: "1個", calories: 300 },
  { name: "カムカム", unit: "1個", calories: 2 },
  { name: "ヤブツバキの実", unit: "1個", calories: 4 },
  { name: "ウグイスカグラ", unit: "1個", calories: 1 },
    { name: "コーラ", unit: "350ml", calories: 150 },
    { name: "サイダー", unit: "350ml", calories: 140 },
    { name: "ジンジャーエール", unit: "350ml", calories: 135 },
    { name: "トニックウォーター", unit: "350ml", calories: 124 },
    { name: "炭酸レモン水", unit: "350ml", calories: 30 },
    { name: "クラフトコーラ", unit: "350ml", calories: 180 },
    { name: "100%オレンジジュース", unit: "200ml", calories: 90 },
    { name: "100%リンゴジュース", unit: "200ml", calories: 95 },
    { name: "100%グレープフルーツジュース", unit: "200ml", calories: 80 },
    { name: "100%パイナップルジュース", unit: "200ml", calories: 100 },
    { name: "100%マンゴージュース", unit: "200ml", calories: 120 },
    { name: "トマトジュース", unit: "200ml", calories: 40 },
    { name: "ザクロジュース", unit: "200ml", calories: 120 },
    { name: "野菜ジュース", unit: "200ml", calories: 50 },
    { name: "ミックスフルーツジュース", unit: "200ml", calories: 110 },
    { name: "カシスジュース", unit: "200ml", calories: 130 },
    { name: "アサイージュース", unit: "200ml", calories: 140 },
    { name: "ブラックカラントジュース", unit: "200ml", calories: 125 },
    { name: "アイスコーヒー", unit: "200ml", calories: 10 },
    { name: "カフェラテ", unit: "200ml", calories: 120 },
    { name: "カプチーノ", unit: "200ml", calories: 140 },
    { name: "カフェモカ", unit: "200ml", calories: 190 },
    { name: "キャラメルマキアート", unit: "200ml", calories: 220 },
    { name: "抹茶ラテ", unit: "200ml", calories: 160 },
    { name: "チャイラテ", unit: "200ml", calories: 180 },
    { name: "ルイボスティー", unit: "200ml", calories: 0 },
    { name: "ジャスミンティー", unit: "200ml", calories: 0 },
    { name: "ウーロン茶", unit: "200ml", calories: 0 },
    { name: "ほうじ茶", unit: "200ml", calories: 0 },
    { name: "玄米茶", unit: "200ml", calories: 0 },
    { name: "青汁", unit: "200ml", calories: 20 },
    { name: "プーアル茶", unit: "200ml", calories: 0 },
    { name: "麦茶", unit: "200ml", calories: 0 },
    { name: "ホットチョコレート", unit: "200ml", calories: 250 },
    { name: "ミルクセーキ", unit: "200ml", calories: 300 },
    { name: "いちごミルク", unit: "200ml", calories: 200 },
    { name: "バナナジュース", unit: "200ml", calories: 220 },
    { name: "乳酸菌飲料", unit: "200ml", calories: 130 },
  
  
    

    
];

document.getElementById("search-bar").addEventListener("input", function () {
    const query = this.value.toLowerCase();
    const suggestionsDiv = document.getElementById("suggestions");
    suggestionsDiv.innerHTML = "";
    suggestionsDiv.style.display = "none";

    if (query) {
        const filteredFoods = foodData.filter(food => food.name.includes(query));
        if (filteredFoods.length > 0) {
            suggestionsDiv.style.display = "block";
            filteredFoods.forEach(food => {
                const div = document.createElement("div");
                div.textContent = `${food.name} (${food.unit}) ${food.calories} kcal`;
                div.classList.add("suggestion");
                div.onclick = () => selectFood(food);
                suggestionsDiv.appendChild(div);
            });
        }
    }
});

function selectFood(food) {
    const selectedFoodsList = document.getElementById("selected-foods");

    // リストアイテムを作成
    const li = document.createElement("li");
    li.textContent = `${food.name} (${food.unit}) - ${food.calories} kcal`;

    // 削除ボタンを追加
    const removeBtn = document.createElement("button");
    removeBtn.textContent = "削除";
    removeBtn.style.marginLeft = "10px";
    removeBtn.onclick = () => {
        selectedFoodsList.removeChild(li);
        updateTotalCalories(-food.calories); // カロリーを減算
    };

    li.appendChild(removeBtn);
    selectedFoodsList.appendChild(li);

    updateTotalCalories(food.calories); // カロリーを加算

    // 🔽 追加: 検索バーのテキストをクリア
    document.getElementById("search-bar").value = "";
    
    // 🔽 追加: サジェストリストを非表示にする
    document.getElementById("suggestions").style.display = "none";
}


function updateTotalCalories(calories) {
    const totalCaloriesElem = document.getElementById("total-calories");
    totalCaloriesElem.textContent = parseInt(totalCaloriesElem.textContent) + calories;
}